profile('SPARQL PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT COUNT(*) WHERE { { ?v6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .  ?v6 dbpowl:abstract ?v1 .  ?v6 rdfs:label ?v2 .  ?v6 geo:lat ?v3 .  ?v6 geo:long ?v4 . OPTIONAL { ?v6 foaf:depiction ?v8 . } } OPTIONAL { ?v6 foaf:homepage ?v10 . } OPTIONAL { ?v6 dbpowl:populationTotal ?v12 . } OPTIONAL { ?v6 dbpowl:thumbnail ?v14 . } }');
profile('SPARQL PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT COUNT(*) WHERE { ?v3 foaf:page ?v0 . ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .  ?v3 dbpprop:position ?v6 .  ?v3 dbpprop:clubs ?v8 .  ?v8 dbpowl:capacity ?v1 . ?v3 dbpowl:birthPlace ?v5 . OPTIONAL { ?v3 dbpowl:number ?v9 . } }');
profile('SPARQL PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT COUNT(*) WHERE { ?v5 dbpowl:thumbnail ?v4 . ?v5 rdf:type ?type . ?v5 rdfs:label ?v . ?v5 foaf:page ?v8 . OPTIONAL { ?v5 foaf:homepage ?v10 . } }');
profile('SPARQL PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX dbpowl: <http://dbpedia.org/ontology/> SELECT COUNT(*) WHERE { { ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type . ?v2 rdfs:label ?v . ?v6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type1 . ?v6 dbpowl:city ?v2 . ?v6 dbpprop:iata ?v5 . OPTIONAL { ?v6 foaf:homepage ?v7 . } } OPTIONAL { ?v6 dbpprop:nativename ?v8 . } }');
profile('SPARQL PREFIX dct: <http://purl.org/dc/terms/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT COUNT(*) WHERE { ?v4 dct:subject ?v . ?v4 foaf:name ?v6 . OPTIONAL { ?v4 rdfs:comment ?v8 . } }');
profile('SPARQL PREFIX dct: <http://purl.org/dc/terms/> PREFIX georss: <http://www.georss.org/georss/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX dbpprop: <http://dbpedia.org/property/> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT COUNT(*) WHERE { ?v0 rdfs:comment ?v1 .  ?v0 foaf:page ?v . OPTIONAL { ?v0 dct:subject ?v6 . } OPTIONAL { ?v0 dbpprop:industry ?v5 . } OPTIONAL { ?v0 dbpprop:location ?v2 . } OPTIONAL { ?v0 dbpprop:locationCountry ?v3 . } OPTIONAL { ?v0 dbpprop:locationCity ?v9 . ?a dbpprop:manufacturer ?v0 . } OPTIONAL { ?v0 dbpprop:products ?v11 . ?b dbpprop:model ?v0 . } OPTIONAL { ?v0 georss:point ?v10 . } OPTIONAL { ?v0 rdf:type ?v7 . } }');
