profile('SPARQL PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT COUNT(*) WHERE { { ?st ub:teachingAssistantOf ?course . OPTIONAL { ?st ub:takesCourse ?course2 . ?pub1 ub:publicationAuthor ?st . } } { ?prof ub:teacherOf ?course . ?st ub:advisor ?prof . OPTIONAL { ?prof ub:researchInterest ?resint . ?pub2 ub:publicationAuthor ?prof . }}}');
profile('SPARQL PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT COUNT(*) WHERE { { ?pub rdf:type ?type . ?pub ub:publicationAuthor ?st . ?pub ub:publicationAuthor ?prof . OPTIONAL { ?st ub:emailAddress ?ste .  ?st ub:telephone ?sttel . }}{ ?st ub:undergraduateDegreeFrom ?univ .  ?dept ub:subOrganizationOf ?univ . OPTIONAL { ?head ub:headOf ?dept . ?others ub:worksFor ?dept . }}{ ?st ub:memberOf ?dept . ?prof ub:worksFor ?dept . OPTIONAL { ?prof ub:doctoralDegreeFrom ?univ1 . ?prof ub:researchInterest ?resint1 . }}}');
profile('SPARQL PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT COUNT(*) WHERE { { ?pub ub:publicationAuthor ?st . ?pub ub:publicationAuthor ?prof . ?st rdf:type ?type . OPTIONAL { ?st ub:undergraduateDegreeFrom ?univ1 . ?st ub:telephone ?sttel . }} { ?st ub:advisor ?prof . OPTIONAL { ?prof ub:doctoralDegreeFrom ?univ .  ?prof ub:researchInterest ?resint . }}{ ?st ub:memberOf ?dept . ?prof ub:worksFor ?dept . ?prof <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type1 . OPTIONAL { ?head ub:headOf ?dept . ?others ub:worksFor ?dept . }}}');
profile('SPARQL PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT COUNT(*) WHERE { ?x ub:worksFor ?dep . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type . OPTIONAL { ?y ub:advisor ?x . ?x ub:teacherOf ?z . ?y ub:takesCourse ?z . }}');
profile('SPARQL PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT COUNT(*) WHERE { ?x ub:worksFor ?dep . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type . OPTIONAL { ?x ub:emailAddress ?y1 . ?x ub:telephone ?y2 . ?x ub:name ?y3 . }}');
