PREFIX u: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { ?x u:subOrganizationOf ?univ . ?x r:type u:ResearchGroup . }
PREFIX u: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { ?x u:worksFor ?univ . ?x r:type u:FullProfessor . ?x u:name ?y1 . ?x u:emailAddress ?y2 . ?x u:telephone ?y3 . }
PREFIX u: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { ?y r:type u:University . ?x u:memberOf ?z . ?z u:subOrganizationOf ?y . ?z r:type u:Department . ?x u:undergraduateDegreeFrom ?y . ?x r:type u:UndergraduateStudent . }
PREFIX u: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { ?y r:type u:University . ?z u:subOrganizationOf ?y . ?z r:type u:Department . ?x u:memberOf ?z . ?x r:type u:GraduateStudent . ?x u:undergraduateDegreeFrom ?y . }
PREFIX u: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> PREFIX r: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT * WHERE { ?y r:type u:FullProfessor . ?y u:teacherOf ?z . ?z r:type u:Course . ?x u:advisor ?y . ?x u:takesCourse ?z . }