PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT * WHERE { { ?pub ub:publicationAuthor ?st . ?pub ub:publicationAuthor ?prof . ?st rdf:type ub:GraduateStudent . OPTIONAL { ?st ub:undergraduateDegreeFrom ?univ1 . ?st ub:telephone ?sttel . }} { ?st ub:advisor ?prof . OPTIONAL { ?prof ub:doctoralDegreeFrom ?univ .  ?prof ub:researchInterest ?resint . }}{ ?st ub:memberOf ?dept . ?prof ub:worksFor ?dept . ?prof <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ub:FullProfessor . OPTIONAL { ?head ub:headOf ?dept . ?others ub:worksFor ?dept . }}}
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT * WHERE { ?x ub:worksFor <http://www.Department9.University9999.edu> . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ub:FullProfessor . OPTIONAL { ?y ub:advisor ?x . ?x ub:teacherOf ?z . ?y ub:takesCourse ?z . }}
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT * WHERE { { ?x ub:worksFor <http://www.Department0.University12.edu> . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ub:FullProfessor . OPTIONAL { ?y ub:advisor ?x . ?x ub:teacherOf ?z . ?y ub:takesCourse ?z . }}}
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#> SELECT * WHERE { ?x ub:worksFor <http://www.Department0.University12.edu> . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ub:FullProfessor . OPTIONAL { ?x ub:emailAddress ?y1 . ?x ub:telephone ?y2 . ?x ub:name ?y3 . }}
