SELECT ?var1 ?var2 ?var3 ?var4 ?var5 ?var6 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11344> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P2102> ?var2 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P2101> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P1108> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P2054> ?var5 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P2067> ?var6 . } }   
