SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q3838065> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q29839252> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q11113294> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q28805366> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q11691299> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q4772725> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q2617392> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q11191267> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q3059692> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q3427121> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q1180302> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q3402530> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q4180402> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q7792073> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q2896440> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q4495159> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q782615> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q458567> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q6175131> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q1387851> . ?var1 <http://www.wikidata.org/prop/direct/P31> ?var2 . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P577> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P179> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P361> ?var4 . } }   
