SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q134041> ?var1 <http://www.wikidata.org/entity/Q19241528> . } OPTIONAL { <http://www.wikidata.org/entity/Q19241528> ?var1 <http://www.wikidata.org/entity/Q134041> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q39844> ?var1 <http://www.wikidata.org/entity/Q222904> . } OPTIONAL { <http://www.wikidata.org/entity/Q222904> ?var1 <http://www.wikidata.org/entity/Q39844> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q3109568> ?var1 <http://www.wikidata.org/entity/Q6581097> . } OPTIONAL { <http://www.wikidata.org/entity/Q6581097> ?var1 <http://www.wikidata.org/entity/Q3109568> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q21908476> ?var1 <http://www.wikidata.org/entity/Q22470743> . } OPTIONAL { <http://www.wikidata.org/entity/Q22470743> ?var1 <http://www.wikidata.org/entity/Q21908476> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q22470743> ?var1 <http://www.wikidata.org/entity/Q21908476> . } OPTIONAL { <http://www.wikidata.org/entity/Q21908476> ?var1 <http://www.wikidata.org/entity/Q22470743> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q4278140> ?var1 <http://www.wikidata.org/entity/Q21942377> . } OPTIONAL { <http://www.wikidata.org/entity/Q21942377> ?var1 <http://www.wikidata.org/entity/Q4278140> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q8495> ?var1 <http://www.wikidata.org/entity/Q11192509> . } OPTIONAL { <http://www.wikidata.org/entity/Q11192509> ?var1 <http://www.wikidata.org/entity/Q8495> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q28165751> ?var1 <http://www.wikidata.org/entity/Q5167130> . } OPTIONAL { <http://www.wikidata.org/entity/Q5167130> ?var1 <http://www.wikidata.org/entity/Q28165751> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q6581072> ?var1 <http://www.wikidata.org/entity/Q867696> . } OPTIONAL { <http://www.wikidata.org/entity/Q867696> ?var1 <http://www.wikidata.org/entity/Q6581072> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q21908474> ?var1 <http://www.wikidata.org/entity/Q21908475> . } OPTIONAL { <http://www.wikidata.org/entity/Q21908475> ?var1 <http://www.wikidata.org/entity/Q21908474> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q134041> ?var1 <http://www.wikidata.org/entity/Q21084440> . } OPTIONAL { <http://www.wikidata.org/entity/Q21084440> ?var1 <http://www.wikidata.org/entity/Q134041> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q4456791> ?var1 <http://www.wikidata.org/entity/Q5167130> . } OPTIONAL { <http://www.wikidata.org/entity/Q5167130> ?var1 <http://www.wikidata.org/entity/Q4456791> . } }   
SELECT ?var1 ?var2 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q11974361> <http://www.wikidata.org/prop/direct/P31> ?var1 . } OPTIONAL { <http://www.wikidata.org/entity/Q11974361> <http://www.wikidata.org/prop/direct/P345> ?var2 . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q25648869> ?var1 <http://www.wikidata.org/entity/Q21908476> . } OPTIONAL { <http://www.wikidata.org/entity/Q21908476> ?var1 <http://www.wikidata.org/entity/Q25648869> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q5013335> ?var1 <http://www.wikidata.org/entity/Q21084440> . } OPTIONAL { <http://www.wikidata.org/entity/Q21084440> ?var1 <http://www.wikidata.org/entity/Q5013335> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q8415> ?var1 <http://www.wikidata.org/entity/Q21908474> . } OPTIONAL { <http://www.wikidata.org/entity/Q21908474> ?var1 <http://www.wikidata.org/entity/Q8415> . } }   
SELECT ?var1 ?var2 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q27835177> <http://www.wikidata.org/prop/direct/P31> ?var1 . } OPTIONAL { <http://www.wikidata.org/entity/Q27835177> <http://www.wikidata.org/prop/direct/P345> ?var2 . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q13460277> ?var1 <http://www.wikidata.org/entity/Q44148> . } OPTIONAL { <http://www.wikidata.org/entity/Q44148> ?var1 <http://www.wikidata.org/entity/Q13460277> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q22980660> ?var1 <http://www.wikidata.org/entity/Q5442715> . } OPTIONAL { <http://www.wikidata.org/entity/Q5442715> ?var1 <http://www.wikidata.org/entity/Q22980660> . } }   
SELECT ?var1 WHERE { OPTIONAL { <http://www.wikidata.org/entity/Q20682500> ?var1 <http://www.wikidata.org/entity/Q12495992> . } OPTIONAL { <http://www.wikidata.org/entity/Q12495992> ?var1 <http://www.wikidata.org/entity/Q20682500> . } }   
