SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w62b94bf" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6750tjt" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6hd9c68" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6t183hm" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6p289k3" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w67f66m9" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6w40df2" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6qp07r0" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w67d331z" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6845t9j" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w69g7ht2" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6rd1tdg" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w64f1x6s" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6348s14" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w68p7fgh" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6kk9v5z" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6pd8b7g" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w64z1jn7" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6mk6g7g" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
SELECT ?var1 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P3430> "w6jd51zs" . OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P18> ?var1 . } }   
