SELECT ?var1 ?var1Label ?var2Label ?var3 ?var4 ?var5 ?var6 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q811534> . ?var1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q213> . ?var1 <http://www.wikidata.org/prop/direct/P131> ?var2 . ?var2 <http://www.wikidata.org/prop/direct/P131> ?var7 . ?var2 <http://www.wikidata.org/prop/direct/P131> <http://www.wikidata.org/entity/Q579648> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P625> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P677> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P2547> ?var5 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P18> ?var6 . } }   
SELECT ?var1 ?var2 ?var3 ?var4 ?var5 WHERE { ?var1 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q16521> . OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P685> ?var2 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P815> ?var3 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P830> ?var4 . } OPTIONAL { ?var1 <http://www.wikidata.org/prop/direct/P3405> ?var5 . } }   
SELECT ?var1 ?var2 ?var3 WHERE { ?var2 <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q39829> . OPTIONAL { } OPTIONAL { } OPTIONAL { } OPTIONAL { ?var2 <http://www.wikidata.org/prop/direct/P212> ?var3 . } }   
